version: '3.9'
services:
  tripbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: tripsit_tripbot
    restart: unless-stopped
    ports:
      - "9229:9229"
    network_mode: "host"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
