# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '16.17.1'
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
    - name: Update npm
      run: npm install -g npm
    - name: Install eslint
      run: npm install -g eslint
    - name: Linting
      run: eslint --ext ts .
    - name: Install dependencies
      run: npm ci
      
  lint:

    runs-on: ubuntu-latest

    steps:

    - name: Linting
      run: eslint --ext ts .
      
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Testing
      run: echo "I would test now!"
      
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm ci
    - name: Build docker image
      run: echo "I would build the docker image now!"
  
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      run: echo "I would deploy the docker image now!"
